all: one.out two.out three.out four.out four_2.out


one.out: one.c 
	gcc -o one.out one.c

two.out: two.c
	gcc -o two.out two.c

three.out: three.c
	gcc -o three.out three.c

four.out: four.c
	gcc -o four.out four.c

four_2.out: four_2.c
	gcc -o four_2.out four_2.c

clean:
	-rm one.out two.out three.out four.out four_2.out